import type { Product } from "./types";

export const featuredProducts: Product[] = [
  {
    id: 1,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB6M0C5WXQhuTYiyuspn-VifhurOVwe7kbIZvUQTtnkGOulWigJlv4JWOTm-sGaVegOIAYgUAmiAMRYtOjJbxLez9tXe6BO1HypwvXLg7bG-Swo5tBbZh1j94lR2G-SnOrDGl5L4fS3uiyXzBMsg1MuGWe4nhm073t1W1HiX5WUT8W6If756WoREEPCPibjsJI8vMwOYb3AKwZicXr6x5hkcJIVoEYrjUqsCwCXwpsgszvhLZw1XWiguADLq2-37xtZT_DlZs31WA",
    title: "Handcrafted Tribal Masks",
    description: "Intricately carved masks reflecting tribal folklore with traditional patterns and symbols.",
    price: 2499,
    originalPrice: 3499,
    rating: 4.8,
    reviewCount: 127,
    availability: 'in-stock',
    category: 'Art & Sculpture',
    artisan: 'Mangal Singh',
    materials: ['Wood', 'Natural pigments', 'Clay'],
    dimensions: '12" x 8" x 4"',
    weight: '300g',
    craftingTime: '3-4 days',
    isHandmade: true,
    isFeatured: true
  },
  {
    id: 2,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAG20eOeKwKTJPI1QIe0mP0XBqztQUddlA_3l4OAVnajlLzHigsricAyBj3X_Icx7Tt9JC6alnaBki-8EIlj9T3ze1dact4GGQ1JbhIlu9Ccrh0ab2zOwW6mbiUuKDOheWAD9vRRbvfRyftp_BkHe4Y-JSNepnftCr8Y3S6zQPX06kwAYW4_gSpMWMvpomi0Wra317Z7qFLIrnOOsQB5YDYyxSypf1dXI5hoInVG8VPSTqWBt2fkNO7quz4UH_shcnMNR3O3bv33A",
    title: "Traditional Jharkhand Textiles",
    description: "Vibrant textiles with unique tribal patterns woven on traditional handlooms.",
    price: 1899,
    rating: 4.6,
    reviewCount: 89,
    availability: 'in-stock',
    category: 'Textiles',
    artisan: 'Sita Devi',
    materials: ['Cotton', 'Natural dyes', 'Traditional thread'],
    dimensions: '6 feet x 4 feet',
    weight: '500g',
    craftingTime: '2-3 weeks',
    isHandmade: true,
    isFeatured: true
  },
  {
    id: 3,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAsrTqgaCriYAquXsNfePyDTUj8UaoQAWIZuOHroyknUHRTW3QXffb7T3BnOWT8rWJb_f8DWVos-j6zSmH7_s1gQc8QdOgJJoryTM7vdDSwQfFd9GobRYk68Rzepgw0JkNAkmu4JeoYh0tvkq59DjkqhOL3uNhRcaFqU-GifMmbgodHd-Aa63POlH_t6Mk3VrOug6CF2btck7MXCXTQqjtiZKKaBQmKp07sy3ob4QZNx6iv5trM5jcxGvIuSUu5Fh8NL8EsTiqIbg",
    title: "Paitkar Paintings",
    description: "Ancient art form depicting tribal life and mythology on handmade scrolls.",
    price: 3299,
    originalPrice: 4199,
    rating: 4.9,
    reviewCount: 203,
    availability: 'low-stock',
    category: 'Paintings',
    artisan: 'Ravi Chitrakar',
    materials: ['Handmade paper', 'Natural colors', 'Traditional brushes'],
    dimensions: '24" x 18"',
    weight: '150g',
    craftingTime: '5-7 days',
    isHandmade: true,
    isFeatured: true
  }
];

export const newArrivals: Product[] = [
  {
    id: 4,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDUfhrDzsKELYgAE27KkW0ZV2VzqT-N1qGKUXfLgzg2sHzk4YblkZvKKSCILFfPKyKLttFRdkGSYbbtFWpSsn0QPmjOXI0r3QGfmG96cuofuBLPi4WYgN-I7wr1aELhcFQAeIXRpgZHriI2-TX7V5sBnJqS4doRAQFasXMZaZOouCcCmCKziIZx8QxOhMak_R9HPXH39Z7pbD29gqW6xh8x7a_Id0QOtDlvuA7_zlbyrnn8FpgR-rqqYnaBFa0I4uax_BYesBMswA",
    title: "Dokra Metal Crafts",
    description: "Exquisite metal crafts using the ancient Dokra lost-wax casting technique.",
    price: 1799,
    rating: 4.7,
    reviewCount: 156,
    availability: 'in-stock',
    category: 'Metal Crafts',
    artisan: 'Ramesh Kumar',
    materials: ['Brass', 'Bell metal', 'Traditional wax'],
    dimensions: '8" height',
    weight: '400g',
    craftingTime: '4-5 days',
    isHandmade: true
  },
  {
    id: 5,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBzM3ZYYYGH35OgQu9TNW5B585mlM3vAJB1ErGbzrS8d5MHc6m3DJpEfrJnWzrzX6Oy2jvi7m7c63qC9i9hmW12UsesEE6lrRL-sdLIDBC_JwKahu5NycaDecFvU-EJysWTZtFKZUXLC-ZVW14Ln-G2bzvsv_Xxb9I-LLRZuRI-OeuppT3-2AiL3uQ_MxlUSny9mOoTebyWIspYOk8sOkeHHDJvweYmw3i61ckT4krE1a1Icil2O9NbWm-eKV1Dh8AckZJM_vmEnw",
    title: "Tribal Jewelry",
    description: "Handcrafted jewelry with traditional designs using authentic tribal motifs.",
    price: 899,
    originalPrice: 1299,
    rating: 4.5,
    reviewCount: 78,
    availability: 'in-stock',
    category: 'Jewelry',
    artisan: 'Kumari Devi',
    materials: ['Silver', 'Brass', 'Natural stones'],
    dimensions: 'Necklace: 18", Earrings: 2.5"',
    weight: '120g',
    craftingTime: '2-3 days',
    isHandmade: true
  },
  {
    id: 6,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCeT8dZvfmK64WbGQm78o7T4rEkvrzNM-A9tWUURta20J5jUHJQIpD3FDvCsBYITZj0CBlZkuqcpwlLzPiXkgNdpEmJzUKQMaX-oUXuHrbKRrwgEafedknfxgXVkIj2p3DhrbwFZ76NQIwC5ayJDQJ-6v1czTmVbWejYFM9ROAcIqy5WsIJ3FbnYxIauBzpqzTi-MIc-p0T12vydOULJ--BXDan6qeRncrzJY3s7uM7AN7B_NfsCpJKY7yH6rvNKWmrWVZx0xrR9Q",
    title: "Bamboo Baskets",
    description: "Beautifully woven bamboo baskets for storage and decoration, eco-friendly choice.",
    price: 599,
    rating: 4.4,
    reviewCount: 92,
    availability: 'in-stock',
    category: 'Home Decor',
    artisan: 'Suresh Mahato',
    materials: ['Bamboo', 'Natural dyes'],
    dimensions: 'Set of 3: Large(14"), Medium(10"), Small(8")',
    weight: '350g',
    craftingTime: '1-2 days',
    isHandmade: true
  },
  {
    id: 7,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAb-L02QJtopi1LKOC6kgScZc1GJuTqlAjGGCRX6_xbt7ejDNH0CRpSCRFw-yi9W7mySL5elCR5yDKBMmvQcsZcN5eEhwcSytEmRGuRoyDhvUARAK7hMu-Id6CMbSUc98XBL6HZeWRXQPC46yGCoZf0EHg67_xwjnztHtFd9EpAmoKxmIpXDodKCMlkmxqFSTvqNtH9kCWmUDToH5QCHR3GdG_bOCfauOFVO_aZun5krwpokiHSSthHCKAToaFdK93uhUjH2cJvvw",
    title: "Tribal Wall Hangings",
    description: "Colorful wall hangings depicting tribal motifs and stories from Jharkhand folklore.",
    price: 1299,
    rating: 4.6,
    reviewCount: 45,
    availability: 'in-stock',
    category: 'Wall Art',
    artisan: 'Maya Devi',
    materials: ['Jute', 'Cotton thread', 'Natural colors'],
    dimensions: '36" x 24"',
    weight: '250g',
    craftingTime: '3-4 days',
    isHandmade: true
  }
];

export const popularItems: Product[] = [
  {
    id: 8,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBssonGVDCxNGBSkeXTAFTXwUAnxWS3-7wCh1WhwOovN1vgJFIaKNSvM_jvUKk_bAKWio7OhTo40gbUkAcPUPnWXDJEvLN-CGVDeHx5ISAEQPAduKywFDeIcGv60ZgyeXdAmgLOPjnXi1iqDqu41t20R75FiruGwc6ko5peuZvfuFv-yErqSt1f6AbxIB-b5RTcDTDV5dnFP1eAkonFNDC9CI8ZbrFnU4Siq-kVxLViFDtkHjy6fA-EiW5Xq2Hz7G7rvDNZupXujw",
    title: "Handloom Sarees",
    description: "Elegant handloom sarees with intricate tribal designs and natural dyes.",
    price: 4299,
    originalPrice: 5699,
    rating: 4.8,
    reviewCount: 234,
    availability: 'in-stock',
    category: 'Textiles',
    artisan: 'Geeta Weaver',
    materials: ['Pure cotton', 'Silk borders', 'Natural dyes'],
    dimensions: '6.5 meters with blouse piece',
    weight: '600g',
    craftingTime: '2-3 weeks',
    isHandmade: true
  },
  {
    id: 9,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDUwdFvVns8dkdhcEnX_eGEKSWhOvCUhtMapLe_ZHW_MKkko6ko1GRogXEoteEE-QQtXn_LOZc0naKkEqXIw2CeqlIze220Bg4uF_bpI7yBZjlC7WspAW4auficgWwo3yAjaJCV6U5vF2K-nhrV5FgHCJmzfbE-IuR1iismdbhlY3QIrGeh-ou5nYuKKu51-GqQa-tI14Lear-GbRc-1xro3DqlyUhUiXWHKDNu6r1wD-s-8bti-g-U4V_tPpCITeJ69UV3S1lxsg",
    title: "Terracotta Pottery",
    description: "Unique terracotta pottery with earthy tones, perfect for home decoration.",
    price: 799,
    rating: 4.3,
    reviewCount: 67,
    availability: 'in-stock',
    category: 'Pottery',
    artisan: 'Pradip Potter',
    materials: ['Natural clay', 'Natural glazes'],
    dimensions: 'Various sizes available',
    weight: '800g',
    craftingTime: '3-5 days',
    isHandmade: true
  },
  {
    id: 10,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAb-L02QJtopi1LKOC6kgScZc1GJuTqlAjGGCRX6_xbt7ejDNH0CRpSCRFw-yi9W7mySL5elCR5yDKBMmvQcsZcN5eEhwcSytEmRGuRoyDhvUARAK7hMu-Id6CMbSUc98XBL6HZeWRXQPC46yGCoZf0EHg67_xwjnztHtFd9EpAmoKxmIpXDodKCMlkmxqFSTvqNtH9kCWmUDToH5QCHR3GdG_bOCfauOFVO_aZun5krwpokiHSSthHCKAToaFdK93uhUjH2cJvvw",
    title: "Traditional Tribal Rugs",
    description: "Handwoven rugs with authentic tribal patterns, adding warmth to any space.",
    price: 2799,
    rating: 4.7,
    reviewCount: 123,
    availability: 'low-stock',
    category: 'Home Decor',
    artisan: 'Anita Weaver',
    materials: ['Wool', 'Cotton', 'Natural dyes'],
    dimensions: '5 feet x 3 feet',
    weight: '2kg',
    craftingTime: '1-2 weeks',
    isHandmade: true
  },
  {
    id: 11,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDUfhrDzsKELYgAE27KkW0ZV2VzqT-N1qGKUXfLgzg2sHzk4YblkZvKKSCILFfPKyKLttFRdkGSYbbtFWpSsn0QPmjOXI0r3QGfmG96cuofuBLPi4WYgN-I7wr1aELhcFQAeIXRpgZHriI2-TX7V5sBnJqS4doRAQFasXMZaZOouCcCmCKziIZx8QxOhMak_R9HPXH39Z7pbD29gqW6xh8x7a_Id0QOtDlvuA7_zlbyrnn8FpgR-rqqYnaBFa0I4uax_BYesBMswA",
    title: "Decorative Metal Lamps",
    description: "Beautiful metal lamps crafted using traditional techniques, creating ambient lighting.",
    price: 1599,
    rating: 4.5,
    reviewCount: 89,
    availability: 'in-stock',
    category: 'Lighting',
    artisan: 'Vikash Metalsmith',
    materials: ['Brass', 'Copper', 'Traditional patterns'],
    dimensions: '12" height x 8" width',
    weight: '600g',
    craftingTime: '2-3 days',
    isHandmade: true
  }
];
